# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
 - stage: built
   jobs:
   - job: job1
     steps:
     - bash: echo built 1stjob
     - bash: echo $(Test)
     - bash: echo $(Build.ArtifactStagingDirectory)
     - bash: ls -R $(System.DefaultWorkingDirectory)
     - task: CopyFiles@2
       inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: '**/'
         TargetFolder: '$(build.artifactstagingdirectory)'
     - task: PublishBuildArtifacts@1
       inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Abhi'
        publishLocation: 'Container'
    



